### ISSUE TITLE
Incorrect encoding for POST request

### ISSUE THREAD

**Issue by dlyash** [Smartling/api-sdk-java#43]
Getting the following error when trying to delete a file, which URI contains special characters:
```
com.smartling.api.sdk.exceptions.SmartlingApiException: VALIDATION_ERROR
Error{key='command.parse.error', message='There was a problem processing your request: Invalid UTF-8 middle byte 0x3f', details=null}
	at com.smartling.api.sdk.file.response.Response.retrieveData(Response.java:58)
	at com.smartling.api.sdk.file.FileApiClientImpl.deleteFile(FileApiClientImpl.java:109)
```

After reviewing the code it looks like a bug in SDK. In [BaseApiClient](https://github.com/Smartling/api-sdk-java/blob/f598b1d6e3da9b51d6503553483e032c7074d96a/api-sdk/src/main/java/com/smartling/api/sdk/BaseApiClient.java#L88) we have:
```
            stringEntity = new StringEntity(gson.toJson(command));
            stringEntity.setContentType(APPLICATION_JSON_TYPE);
            stringEntity.setContentEncoding(CharEncoding.UTF_8);
```
However, the one-arg. constructor of the `StringEntity` uses *default encoding* to convert a string to bytes.
Thus, we have a payload serialized with `ISO-8859-1` while headers say that it's `UTF-8`

**Comment by dlyash** [comment]
@Hustred could you please review as well?
